ALTER TABLE users ADD COLUMN wants_proxy BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN dm_participate VARCHAR(16) NOT NULL DEFAULT 'no';
ALTER TABLE users ADD COLUMN dm_send_emails BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN proxy_id UUID;
ALTER TABLE sample_votes ADD COLUMN in_sample BOOLEAN NOT NULL DEFAULT true;
