export const DIRECTION = {
    UP: 2,
    NONE : 1,
    DOWN : 0
}
export const TYPE = {
    REQUEST_POST_QUARANTINE: 0,
    REQUEST_POST_TRUTH: 1,
    POST_SAMPLE_QUARANTINE_LVL_1: 2,
    POST_SAMPLE_QUARANTINE_REFERENDUM: 3,
    POST_SAMPLE_TRUTH_LVL_1: 4,
    POST_SAMPLE_TRUTH_REFERENDUM: 5,
}